### ISSUE TITLE
Scroll Wheel Clicked

### ISSUE THREAD

**Issue by celticsamurai** [raleighlittles/Tourbox_Neo_Linux_Driver#6] opened 2023-10-28 19:05 UTC
Whenever I launch this, all the command prompt gives me is:
<code>
Scroll wheel clicked
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
00 �
01 �
0
 �
Scroll wheel clicked
</code>
And it keeps looping.

**Comment by raleighlittles** [comment] 2024-01-13 20:48
@celticsamurai Is this on a Tourbox Neo or a Tourbox Elite Model?

If it's a TourBox Neo:

* What Linux distribution are you using and what version?
* Can you paste the kernel log into here?

**Comment by celticsamurai** [comment] 2024-01-24 02:04
> @celticsamurai Is this on a Tourbox Neo or a Tourbox Elite Model?
> 
> If it's a TourBox Neo:
> 
>     * What Linux distribution are you using and what version?
> 
>     * Can you paste the kernel log into here?

It is a Neo. I'm using Arch Linux. Where should I look to get the kernel log?

**Comment by raleighlittles** [comment] 2024-01-24 03:52
Run `sudo dmesg -wT`, press enter a few times, then connect your Tourbox Neo, and reproduce the issue. Close the log, and copy everything back to where you pressed enter, then paste it here.

Do any of the other buttons work at all? Or are you getting no events whatsoever other than the log repeatedly printing that out over and over?

**Comment by celticsamurai** [comment] 2024-02-10 22:34
> Run `sudo dmesg -wT`, press enter a few times, then connect your Tourbox Neo, and reproduce the issue. Close the log, and copy everything back to where you pressed enter, then paste it here.
> 
When I reproduce the issue, does it need to be within the same command line? Because when I tried to do that, nothing seemed to happen. Also, where would that command send the log for me to attach?

> Do any of the other buttons work at all? Or are you getting no events whatsoever other than the log repeatedly printing that out over and over?

I'm not getting any other events whatsoever.

**Comment by raleighlittles** [comment] 2024-04-08 03:43
I was not able to reproduce this issue just now. I could see event inputs from some events and I didn't see the Scroll Wheel clicked message appearing constantly.

![image](https://github.com/raleighlittles/Tourbox_Neo_Linux_Driver/assets/2137201/02455d62-d9ea-4c84-a751-cb2d4e043e59)

**Comment by raleighlittles** [comment] 2024-04-08 03:49
https://github.com/raleighlittles/Tourbox_Neo_Linux_Driver/assets/2137201/6a5c4c17-8f12-4aab-b08b-d60b9fc6e047

I even tried to record a small video (I have no idea why the frame rate was so messed up), but you can see me pressing buttons and some events being correctly shown on the console

**Comment by raleighlittles** [comment] 2024-04-14 19:18
Closing due to inability to reproduce, see comment above

**Closed as completed by raleighlittles** 2024-04-14 19:18 UTC
Labels: bug
